// NOIRÉ 2 — Contact page
// Generated by scripts/framer-pages.mts from the Next.js pages — edit content
// there (content/*.ts) and regenerate, or edit the props here directly.
import { addPropertyControls, ControlType } from "framer"
import type { CSSProperties } from "react"
// Section code files, imported by their Framer module URL (untyped, hence ts-ignore).
// @ts-ignore
import NoireContact from "https://framer.com/m/NoireContact-gw5yxx.js"
// @ts-ignore
import NoirePageHero from "https://framer.com/m/NoirePageHero-ubNajh.js"

const C: Record<string, any> = { NoireContact, NoirePageHero }

const PAGES: Record<string, { name: string; props: Record<string, any> }[]> = {"main":[{"name":"NoirePageHero","props":{"label":"Contact","title":"Let’s talk about","accent":"what you’re making.","lede":"A real person reads every message — usually the founder — and replies within two working days.","meta":"","image":{"src":"https://raw.githubusercontent.com/uxuimonir/2nd/dfc52ae6763df67bd2e5dc8f8b76bac7d8ec60f1/noire/public/media/hero-contact.webp","alt":"A glowing opal globe lamp on a dark floor."},"imagePosition":"50% 50%","imageRatio":1.78,"dark":true}},{"name":"NoireContact","props":{"endpoint":"","email":"hello@noire.example","availability":"Booking projects from January 2027","location":"Lisbon, Portugal","timeZone":"Europe/Lisbon","projectTypes":"Identity, Exhibition, Editorial / book, Spatial, Digital, Art direction, Something else","budgets":"Under €15k, €15k – €40k, €40k – €80k, €80k +, Not sure yet","image":{"src":"https://raw.githubusercontent.com/uxuimonir/2nd/dfc52ae6763df67bd2e5dc8f8b76bac7d8ec60f1/noire/public/media/contact-studio.webp","alt":""}}}]}

/**
 * @framerSupportedLayoutWidth fixed
 * @framerSupportedLayoutHeight auto
 * @framerIntrinsicWidth 1440
 */
export default function NoireContactPage(props: { page?: string; style?: CSSProperties }) {
    const sections = PAGES[props.page ?? "main"] ?? PAGES["main"]
    return (
        <div style={{ ...props.style, width: "100%", display: "flex", flexDirection: "column" }}>
            {sections.map((s, i) => {
                const Section = C[s.name]
                return <Section key={i} {...s.props} />
            })}
        </div>
    )
}

addPropertyControls(NoireContactPage, {
    
})
