// NOIRÉ 2 — Recognition page
// Generated by scripts/framer-pages.mts from the Next.js pages — edit content
// there (content/*.ts) and regenerate, or edit the props here directly.
import { addPropertyControls, ControlType } from "framer"
import type { CSSProperties } from "react"
// Section code files, imported by their Framer module URL (untyped, hence ts-ignore).
// @ts-ignore
import NoireBlocks from "https://framer.com/m/NoireBlocks-jOf6Km.js"
// @ts-ignore
import NoirePageHero from "https://framer.com/m/NoirePageHero-ubNajh.js"

const C: Record<string, any> = { NoireBlocks, NoirePageHero }

const PAGES: Record<string, { name: string; props: Record<string, any> }[]> = {"main":[{"name":"NoirePageHero","props":{"label":"Recognition","title":"Awards, shows,","accent":"talks & print.","lede":"10 entries. All are fictional demo content — replace them with your own.","meta":"","imageRatio":1.78,"dark":false}},{"name":"NoireBlocks","props":{"variant":"rows","label":"Index","heading":"","accent":"","text":"","caption":"","dark":false,"items":[{"a":"2026 · Exhibition","b":"Quiet Matter","c":"Halde Kunsthalle, Bergen. Identity and catalogue for the survey exhibition.","link":"/work/quiet-matter"},{"a":"2026 · Talk","b":"Designing for slow looking","c":"Northern Design Days (demo). On exhibition graphics that support attention.","link":""},{"a":"2025 · Award","b":"Book of the Year, shortlist","c":"Independent Book Design Prize (demo). For Ninefold, Ferro Editions.","link":"/work/ninefold"},{"a":"2025 · Award","b":"Heritage reuse, shortlist","c":"Regional Architecture & Design Awards (demo). Spatial identity for Baía Baths.","link":"/work/tidewater"},{"a":"2025 · Publication","b":"Tiles that talk","c":"Surface Quarterly, issue 18 (demo). Feature on the Tidewater signage system.","link":"/work/tidewater"},{"a":"2024 · Publication","b":"Photographing by lamplight","c":"Interior Notes (demo). Interview on the Lowlight campaign.","link":"/work/lowlight"},{"a":"2024 · Talk","b":"An identity you fire","c":"Material Matters symposium (demo). With Kiln Room, on stamps and seasonal drift.","link":"/work/field-notes-on-clay"},{"a":"2023 · Milestone","b":"Index of Rooms launches","c":"Marrow Architects. 1,200 rooms indexed across thirty years of work.","link":"/work/index-of-rooms"},{"a":"2022 · Exhibition","b":"Paper Weather","c":"Studio show, Lisbon. Fifty-two risograph prints hung in sequence.","link":"/work/paper-weather"},{"a":"2021 · Milestone","b":"Studio founded","c":"Lisbon. Noiré opens in a former print shop.","link":""}]}}]}

/**
 * @framerSupportedLayoutWidth fixed
 * @framerSupportedLayoutHeight auto
 * @framerIntrinsicWidth 1440
 */
export default function NoireRecognitionPage(props: { page?: string; style?: CSSProperties }) {
    const sections = PAGES[props.page ?? "main"] ?? PAGES["main"]
    return (
        <div style={{ ...props.style, width: "100%", display: "flex", flexDirection: "column" }}>
            {sections.map((s, i) => {
                const Section = C[s.name]
                return <Section key={i} {...s.props} />
            })}
        </div>
    )
}

addPropertyControls(NoireRecognitionPage, {
    
})
