// NOIRÉ 2 — Colophon page
// Generated by scripts/framer-pages.mts from the Next.js pages — edit content
// there (content/*.ts) and regenerate, or edit the props here directly.
import { addPropertyControls, ControlType } from "framer"
import type { CSSProperties } from "react"
// Section code files, imported by their Framer module URL (untyped, hence ts-ignore).
// @ts-ignore
import NoireArticle from "https://framer.com/m/NoireArticle-8FjatC.js"

const C: Record<string, any> = { NoireArticle }

const PAGES: Record<string, { name: string; props: Record<string, any> }[]> = {"main":[{"name":"NoireArticle","props":{"category":"Colophon","title":"How this site is made.","date":"","author":"","excerpt":"A short record of the decisions behind the design — for anyone curious, or anyone customising it.","body":"## Typefaces\n\nInstrument Serif for statements, titles and the wordmark — used large, with tight tracking and italics for emphasis. Inter Tight for navigation, metadata, captions, forms and body copy.\n\n## Colour\n\nWarm off-white #F5F2EC and near-black #11110F as a true light/dark pairing, a surface tone #EAE6DE, muted text #6D6A64, hairlines #D3CFC6 and one accent — vermilion #D9573F — kept to a small share of every screen.\n\n## Imagery\n\nEvery image in this demo is original, procedurally rendered artwork made for the template — stone, water, paper, light, clay, concrete, linen, print and pencil studies, graded together with soft contrast and a light grain. Replace them with your own photography.\n\n## Motion\n\nQuietly cinematic: mask reveals on titles, a hero that settles as you scroll, project cards that stack, a manifesto that lights up word by word. With reduced motion enabled, movement is removed and content appears immediately.\n\n## Build\n\nNOIRÉ 2 v2.0.0. Every section is a self-contained Framer code component with property controls, also used to render this Next.js site. Content lives in typed collections that mirror a Framer CMS.\n\n## Content\n\nNoiré Studio (demo), its people, clients, projects, awards and figures are fictional.","backLabel":"Back home","backLink":"/","prevLabel":"","prevLink":"","nextLabel":"Privacy","nextLink":"/privacy"}}]}

/**
 * @framerSupportedLayoutWidth fixed
 * @framerSupportedLayoutHeight auto
 * @framerIntrinsicWidth 1440
 */
export default function NoireColophonPage(props: { page?: string; style?: CSSProperties }) {
    const sections = PAGES[props.page ?? "main"] ?? PAGES["main"]
    return (
        <div style={{ ...props.style, width: "100%", display: "flex", flexDirection: "column" }}>
            {sections.map((s, i) => {
                const Section = C[s.name]
                return <Section key={i} {...s.props} />
            })}
        </div>
    )
}

addPropertyControls(NoireColophonPage, {
    
})
