import type { City } from "@/types/content";

/** The eight divisional cities. Coordinates are city centres. */
export const cities: City[] = [
  {
    slug: "dhaka",
    name: "Dhaka",
    nameBn: "ঢাকা",
    region: "dhaka",
    coordinates: [90.4125, 23.8103],
    tagline: "A river city that became a megacity.",
    summary: "The capital grew from Mughal Jahangirnagar on the Buriganga into one of the most densely populated cities on earth.",
    description: [
      "Dhaka's story begins on the water. In 1610 the Mughal governor Islam Khan made it the provincial capital of Bengal, and the city on the Buriganga became Jahangirnagar. Lalbagh Fort, the Bara Katra and the lanes of Old Dhaka still hold that layer.",
      "The nineteenth century added the pink palace of Ahsan Manzil; the twentieth added Curzon Hall, the University of Dhaka and, after independence, Louis Kahn's National Parliament House.",
      "Today the city moves by cycle rickshaw, bus, boat and — since December 2022 — an elevated metro. Its painted rickshaws are recognised by UNESCO as intangible cultural heritage.",
    ],
    rivers: ["buriganga"],
    landmarks: ["Ahsan Manzil", "Lalbagh Fort", "National Parliament House", "Central Shaheed Minar", "Hatirjheel", "Sadarghat"],
    facts: [
      { label: "Mughal capital from", value: "1610" },
      { label: "University of Dhaka", value: "Founded 1921" },
      { label: "Metro Rail (MRT Line 6)", value: "First section opened 28 Dec 2022" },
    ],
    heritage: ["ahsan-manzil", "lalbagh-fort", "national-parliament-house", "central-shaheed-minar", "curzon-hall"],
    nature: [],
    food: ["kacchi-biryani", "fuchka"],
    media: ["hatirjheel-night", "dhaka-rickshaw-parking", "dhaka-rickshaw-view", "parliament"],
    ambient: "city",
  },
  {
    slug: "chattogram",
    name: "Chattogram",
    nameBn: "চট্টগ্রাম",
    region: "chattogram",
    coordinates: [91.7832, 22.3569],
    tagline: "The port between the hills and the sea.",
    summary: "Bangladesh's principal seaport sits where the Karnaphuli meets the Bay of Bengal, backed by green hills.",
    description: [
      "For centuries traders from Arabia, Persia and Southeast Asia knew Chattogram as a harbour. The port on the Karnaphuli handles the majority of the country's seaborne trade today.",
      "The city is also the gateway to the Hill Tracts and to the coast running south toward Cox's Bazar. In 2023 a road tunnel opened beneath the Karnaphuli, linking the city to the river's southern bank.",
    ],
    rivers: ["karnaphuli"],
    landmarks: ["Port of Chattogram", "Patenga", "Karnaphuli River", "Foy's Lake"],
    facts: [
      { label: "River", value: "Karnaphuli" },
      { label: "Karnaphuli tunnel", value: "Opened 2023" },
    ],
    heritage: [],
    nature: ["coxs-bazar", "sajek-valley", "nilgiri-bandarban", "saint-martins-island"],
    food: [],
    media: ["karnaphuli-night"],
    ambient: "sea",
  },
  {
    slug: "sylhet",
    name: "Sylhet",
    nameBn: "সিলেট",
    region: "sylhet",
    coordinates: [91.8687, 24.8949],
    tagline: "Tea, shrines and the Surma.",
    summary: "A city on the Surma surrounded by tea estates, wetlands and the foothills of Meghalaya.",
    description: [
      "Sylhet sits on the north bank of the Surma. The Keane Bridge, opened in the 1930s, and the Ali Amjad clock tower mark the riverfront.",
      "The shrine of the fourteenth-century saint Shah Jalal draws pilgrims from across the country, while the surrounding hills hold many of Bangladesh's tea gardens. Many Bangladeshis in the United Kingdom trace their roots to the region.",
    ],
    rivers: ["surma"],
    landmarks: ["Keane Bridge", "Shah Jalal shrine", "Ali Amjad's Clock", "Malnicherra Tea Garden"],
    facts: [
      { label: "River", value: "Surma" },
      { label: "Landscape", value: "Tea hills & haor wetlands" },
    ],
    heritage: [],
    nature: ["ratargul-swamp-forest", "srimangal-tea-gardens", "tanguar-haor", "jaflong"],
    food: [],
    media: ["keane-bridge", "tea-malnicherra"],
    ambient: "rain",
  },
  {
    slug: "rajshahi",
    name: "Rajshahi",
    nameBn: "রাজশাহী",
    region: "rajshahi",
    coordinates: [88.6042, 24.3745],
    tagline: "Silk, mangoes and the Padma at sunset.",
    summary: "A green riverside city known for its university, its silk and the mango country around it.",
    description: [
      "Rajshahi faces the Padma, and its embankments are where the city gathers in the evening to watch the river. The Varendra Research Museum, founded in 1910, holds one of the country's major collections of Pala-era sculpture and inscriptions.",
      "Silk weaving and the mango orchards of the surrounding districts — Chapai Nawabganj above all — give the region its seasonal rhythm.",
    ],
    rivers: ["padma"],
    landmarks: ["Padma embankment (T-badh)", "Varendra Research Museum", "University of Rajshahi"],
    facts: [
      { label: "River", value: "Padma" },
      { label: "Varendra Research Museum", value: "Founded 1910" },
    ],
    heritage: ["somapura-mahavihara", "mahasthangarh"],
    nature: [],
    food: ["fuchka"],
    media: ["rajshahi-padma", "rajshahi-t-badh"],
    ambient: "river",
  },
  {
    slug: "khulna",
    name: "Khulna",
    nameBn: "খুলনা",
    region: "khulna",
    coordinates: [89.5403, 22.8456],
    tagline: "Gateway to the mangroves.",
    summary: "An industrial river city on the Rupsha, a starting point for journeys into the Sundarbans.",
    description: [
      "Khulna grew on the banks of the Rupsha and Bhairab rivers. Downstream, the river becomes the Pasur and passes Mongla port before entering the Sundarbans.",
      "The region's shrimp farms and the nearby Mosque City of Bagerhat make it a meeting point of ecology, economy and heritage.",
    ],
    rivers: ["pasur"],
    landmarks: ["Rupsha Bridge", "Mongla port (nearby)", "Bagerhat (nearby)"],
    facts: [
      { label: "River", value: "Rupsha → Pasur" },
      { label: "Nearby", value: "Sundarbans, Bagerhat" },
    ],
    heritage: ["sixty-dome-mosque"],
    nature: ["sundarbans"],
    food: ["chingri"],
    media: ["rupsha-bridge", "sundarbans-kachikhali"],
    ambient: "river",
  },
  {
    slug: "barishal",
    name: "Barishal",
    nameBn: "বরিশাল",
    region: "barishal",
    coordinates: [90.3535, 22.701],
    tagline: "Where the delta travels by river.",
    summary: "A river port on the Kirtankhola, linked to Dhaka by overnight multi-deck launches.",
    description: [
      "Barishal has long been called the 'Venice of Bengal' for its rivers and canals. The launch terminal on the Kirtankhola is the city's front door: every evening the great river launches leave for Dhaka.",
      "The surrounding district is known for floating markets, guava orchards and the rice-and-fish economy of the lower delta.",
    ],
    rivers: ["meghna"],
    landmarks: ["Barishal river port", "Kirtankhola River", "Floating markets (region)"],
    facts: [{ label: "River", value: "Kirtankhola" }],
    heritage: [],
    nature: [],
    food: ["hilsa"],
    media: ["barishal-launch", "kirtankhola"],
    ambient: "river",
  },
  {
    slug: "rangpur",
    name: "Rangpur",
    nameBn: "রংপুর",
    region: "rangpur",
    coordinates: [89.2752, 25.7439],
    tagline: "The northern plains and the Teesta.",
    summary: "A northern city of palaces and plains, close to the Teesta and the Kantajew Temple.",
    description: [
      "Rangpur is the principal city of the north. Tajhat Palace, built by a zamindar family in the early twentieth century, now houses a museum.",
      "The Teesta — flowing down from Sikkim — shapes the farmland of the region before it joins the Brahmaputra.",
    ],
    rivers: ["teesta"],
    landmarks: ["Tajhat Palace", "Carmichael College", "Teesta Barrage (region)"],
    facts: [{ label: "River", value: "Teesta (region)" }],
    heritage: ["kantajew-temple"],
    nature: [],
    food: [],
    media: ["tajhat", "teesta-barrage"],
    ambient: "rain",
  },
  {
    slug: "mymensingh",
    name: "Mymensingh",
    nameBn: "ময়মনসিংহ",
    region: "mymensingh",
    coordinates: [90.4203, 24.7471],
    tagline: "A city on the Old Brahmaputra.",
    summary: "A riverside city of zamindar houses, folk ballads and an agricultural university.",
    description: [
      "Mymensingh stands on the Old Brahmaputra, once the main course of the great river. Shashi Lodge, built by the Muktagacha zamindars in the early twentieth century, is among its landmarks.",
      "The region's folk ballads — the Mymensingh Gitika — were collected in the 1920s and remain a pillar of Bengali literature.",
    ],
    rivers: ["old-brahmaputra"],
    landmarks: ["Shashi Lodge", "Old Brahmaputra riverside", "Bangladesh Agricultural University"],
    facts: [{ label: "River", value: "Old Brahmaputra" }],
    heritage: [],
    nature: [],
    food: [],
    media: ["shashi-lodge", "paddy"],
    ambient: "river",
  },
];
