import type { CultureItem } from "@/types/content";

export const culture: CultureItem[] = [
  {
    slug: "bangla-language",
    name: "Bangla",
    nameBn: "বাংলা",
    category: "language",
    coordinates: [90.3966, 23.7271],
    region: "dhaka",
    recognition: "21 February — International Mother Language Day (UNESCO, 1999)",
    summary: "The language at the heart of the nation — defended in 1952, celebrated worldwide every 21 February.",
    description: [
      "Bangla is one of the most widely spoken languages in the world. Its own script, descended from Brahmi, carries a literature that runs from the medieval Charyapada to Tagore, Nazrul and today's novelists.",
      "When Pakistan's government proposed Urdu as the sole state language, students in Dhaka resisted. The deaths of 21 February 1952 turned the Language Movement into the seed of national identity.",
    ],
    media: ["language-movement-1952", "shaheed-minar"],
  },
  {
    slug: "baul",
    name: "Baul Songs",
    nameBn: "বাউল গান",
    category: "music",
    coordinates: [89.13, 23.9],
    region: "khulna",
    recognition: "UNESCO Intangible Cultural Heritage (proclaimed 2005)",
    summary: "The songs of wandering mystic minstrels, sung to the one-stringed ektara.",
    description: [
      "Bauls reject caste and creed, seeking the divine within the human body and heart. Their songs, accompanied by the ektara and dotara, are carried from village to village.",
      "The nineteenth-century mystic Lalon Shah, whose shrine is at Chheuriya in Kushtia, is the tradition's most beloved voice. Each year his followers gather there to sing through the night.",
    ],
    media: ["baul", "ektara"],
  },
  {
    slug: "jamdani",
    name: "Jamdani",
    nameBn: "জামদানি",
    category: "craft",
    coordinates: [90.58, 23.79],
    region: "dhaka",
    recognition: "UNESCO Intangible Cultural Heritage (2013)",
    summary: "Fine cotton muslin with patterns woven directly on the handloom, thread by thread.",
    description: [
      "Jamdani is the descendant of Dhaka's legendary muslin. Weavers on the banks of the Sitalakhya, around Rupganj and Sonargaon, insert each motif by hand as they weave, without drawing it first.",
      "A single sari can take weeks or months. The knowledge passes from master to apprentice on the loom.",
    ],
    media: ["jamdani-weaving", "jamdani-weaving-2"],
  },
  {
    slug: "nakshi-kantha",
    name: "Nakshi Kantha",
    nameBn: "নকশী কাঁথা",
    category: "craft",
    coordinates: [89.95, 24.92],
    region: "mymensingh",
    summary: "Embroidered quilts layered from old saris — family stories told in running stitch.",
    description: [
      "Women layer worn saris and stitch them together with thread drawn from the borders. The running stitches form lotuses, fish, boats, wheels of life and scenes from the village.",
      "Jasimuddin's 1929 narrative poem 'Nakshi Kanthar Math' made the kantha a symbol of love and memory in Bengali literature.",
    ],
    media: ["nakshi-kantha-maker", "nakshi-kantha"],
  },
  {
    slug: "pottery",
    name: "Pottery",
    nameBn: "মৃৎশিল্প",
    category: "craft",
    coordinates: [91.17, 23.43],
    region: "chattogram",
    summary: "Clay from the rivers, shaped by families of potters into vessels, toys and terracotta.",
    description: [
      "Pottery is among the oldest crafts of the delta — the terracotta plaques of Paharpur and Mahasthangarh prove it. Potter communities in places such as Bijoypur near Cumilla and Munshiganj still shape river clay by hand and fire it in kilns.",
    ],
    media: ["potters", "pottery-drying", "pottery-art"],
  },
  {
    slug: "pohela-boishakh",
    name: "Pohela Boishakh",
    nameBn: "পহেলা বৈশাখ",
    category: "festival",
    coordinates: [90.397, 23.733],
    region: "dhaka",
    recognition: "Mangal Shobhajatra — UNESCO Intangible Cultural Heritage (2016)",
    summary: "The Bengali New Year — dawn songs, red and white, and a procession of giant folk-art masks.",
    description: [
      "On the first day of Boishakh, Dhaka wakes to songs under the banyan at Ramna. Students of the Faculty of Fine Arts lead a procession of giant masks and figures drawn from folk art, a tradition begun in 1989.",
    ],
    media: ["mangal-shobhajatra", "mongol-shobhajatra-07"],
  },
  {
    slug: "rickshaw-art",
    name: "Rickshaw Painting",
    nameBn: "রিকশা চিত্র",
    category: "art",
    coordinates: [90.41, 23.75],
    region: "dhaka",
    recognition: "UNESCO Intangible Cultural Heritage (2023) — Rickshaws and rickshaw painting in Dhaka",
    summary: "The mobile gallery of Dhaka — hand-painted birds, film stars, cityscapes and flowers.",
    description: [
      "Dhaka's cycle rickshaws are decorated with painted tin panels, tassels and plastic flowers. Painters work in small workshops in Old Dhaka, and their art rolls through the city every day.",
    ],
    media: ["dhaka-rickshaw-parking", "rickshaw-wallah"],
  },
  {
    slug: "literature",
    name: "Literature",
    nameBn: "সাহিত্য",
    category: "literature",
    summary: "From the Charyapada to Tagore, Nazrul and Jasimuddin — a literature carried by rivers and songs.",
    description: [
      "Rabindranath Tagore, winner of the 1913 Nobel Prize in Literature, wrote 'Amar Shonar Bangla', the national anthem; he spent years on the family estates at Shilaidaha on the Padma. Kazi Nazrul Islam, the rebel poet, is the national poet.",
      "Jasimuddin, the 'poet of the villages', gave rural Bengal its voice. The folk ballads of Mymensingh, collected in the 1920s, preserved stories sung for generations.",
    ],
    media: ["curzon-hall"],
  },
];
