import type { Food } from "@/types/content";

export const food: Food[] = [
  {
    slug: "hilsa",
    name: "Hilsa (Ilish)",
    nameBn: "ইলিশ",
    region: "chattogram",
    coordinates: [90.65, 23.23],
    origin: "Chandpur, where the Padma meets the Meghna",
    season: "Monsoon",
    category: "fish",
    summary: "The national fish — silver, oily and swimming upriver from the sea to spawn.",
    description: [
      "Hilsa migrate from the Bay of Bengal up the great rivers to spawn, and Chandpur at the Padma–Meghna confluence is the name every Bangladeshi connects with them. Seasonal fishing bans protect the fish during spawning.",
      "Shorshe ilish — hilsa steamed in mustard paste — is the classic preparation. Bangladeshi hilsa received geographical-indication status in 2017.",
    ],
    media: ["hilsa", "hilsa-dhaka"],
  },
  {
    slug: "kacchi-biryani",
    name: "Kacchi Biryani",
    nameBn: "কাচ্চি বিরিয়ানি",
    region: "dhaka",
    coordinates: [90.4, 23.715],
    origin: "Old Dhaka",
    category: "festive",
    summary: "Marinated raw mutton and fragrant rice, sealed and slow-cooked together — the feast of Old Dhaka.",
    description: [
      "Kacchi means 'raw': the meat goes into the pot uncooked, layered with rice, potatoes and saffron, and the whole is sealed and cooked slowly. It is the dish of weddings and celebrations, served with a spiced yoghurt drink, borhani.",
    ],
    media: ["kacchi"],
  },
  {
    slug: "bhuna-khichuri",
    name: "Bhuna Khichuri",
    nameBn: "ভুনা খিচুড়ি",
    region: "dhaka",
    coordinates: [90.42, 23.78],
    origin: "Everywhere — especially on a rainy day",
    season: "Monsoon",
    category: "rice",
    summary: "Rice and lentils fried with spices — the country's rainy-day comfort.",
    description: [
      "When the monsoon rain comes down, kitchens across Bangladesh make khichuri: rice and lentils cooked with ghee, onion and whole spices, often with egg, beef or chicken, fried aubergine and pickle on the side.",
    ],
    media: ["bhuna-khichuri"],
  },
  {
    slug: "fuchka",
    name: "Fuchka",
    nameBn: "ফুচকা",
    region: "rajshahi",
    coordinates: [88.6, 24.37],
    origin: "Street stalls in every city",
    category: "street",
    summary: "Crisp hollow shells filled with spiced chickpeas and potato, dipped in tamarind water.",
    description: [
      "Fuchka is eaten standing at a stall, one after another, as fast as the vendor can fill them — with spiced mash, egg, chilli and sour tamarind water. It is the country's most social snack.",
    ],
    media: ["fuchka"],
  },
  {
    slug: "bhorta",
    name: "Bhorta",
    nameBn: "ভর্তা",
    region: "mymensingh",
    coordinates: [90.42, 24.75],
    origin: "Home kitchens across the country",
    category: "everyday",
    summary: "Mashed vegetables, lentils or fish with mustard oil, onion and green chilli.",
    description: [
      "Almost anything can become bhorta: aubergine, potato, dried fish, lentils, even hilsa. Mashed by hand with raw mustard oil, onion and chilli, several kinds are served together with plain rice.",
    ],
    media: ["bhorta"],
  },
  {
    slug: "pitha",
    name: "Pitha",
    nameBn: "পিঠা",
    region: "rangpur",
    coordinates: [89.28, 25.74],
    origin: "Villages across the country, after the harvest",
    season: "Winter",
    category: "festive",
    summary: "Rice cakes of winter — steamed, fried, carved or soaked in date-palm molasses.",
    description: [
      "After the Aman harvest, new rice and fresh date-palm juice make winter the season of pitha. Bhapa pitha is steamed with coconut and molasses; chitoi is cooked in clay moulds; nakshi pitha is carved with patterns as intricate as embroidery.",
    ],
    media: ["pitha-nakshi", "pitha-chitoi"],
  },
  {
    slug: "chingri",
    name: "Chingri",
    nameBn: "চিংড়ি",
    region: "khulna",
    coordinates: [89.54, 22.84],
    origin: "Khulna, Bagerhat and Satkhira",
    category: "fish",
    summary: "Prawns from the tidal south-west — cooked in coconut milk as chingri malaikari.",
    description: [
      "The brackish waters of the south-west support extensive shrimp and prawn farming. At home, chingri is cooked with coconut milk, with gourd, or simply fried with onion and chilli.",
    ],
    media: ["chingri"],
  },
  {
    slug: "mishti-doi",
    name: "Mishti Doi",
    nameBn: "মিষ্টি দই",
    region: "rajshahi",
    coordinates: [89.37, 24.85],
    origin: "Bogura",
    category: "sweet",
    summary: "Sweet curd set in clay pots — Bogura's most famous export.",
    description: [
      "Milk is thickened, sweetened and left to set in unglazed clay pots, which draw off moisture and give the curd its dense texture. Bogura's doi is known across the country.",
    ],
    media: ["mishti-doi"],
  },
  {
    slug: "roshogolla",
    name: "Roshogolla",
    nameBn: "রসগোল্লা",
    region: "dhaka",
    coordinates: [90.41, 23.73],
    origin: "Sweet shops across Bengal",
    category: "sweet",
    summary: "Soft balls of fresh chhena cooked in light syrup.",
    description: [
      "Chhena — fresh cheese — is kneaded, rolled into balls and simmered in sugar syrup until spongy. Every sweet shop has its own, and every town claims the best.",
    ],
    media: ["roshogolla", "mishti-mela"],
  },
  {
    slug: "sandesh",
    name: "Sandesh",
    nameBn: "সন্দেশ",
    region: "dhaka",
    coordinates: [90.43, 23.72],
    origin: "Sweet shops across Bengal",
    category: "sweet",
    summary: "A delicate sweet of chhena and sugar, pressed into moulds.",
    description: [
      "Sandesh is chhena cooked gently with sugar or molasses — in winter, with date-palm jaggery — and pressed into carved moulds.",
    ],
    media: ["sandesh"],
  },
];
