import type { HeritageSite } from "@/types/content";

export const heritage: HeritageSite[] = [
  {
    slug: "somapura-mahavihara",
    name: "Somapura Mahavihara",
    nameBn: "সোমপুর মহাবিহার",
    region: "rajshahi",
    coordinates: [88.9769, 25.0311],
    period: "Late 8th century CE · Pala dynasty",
    timeline: "somapura",
    architecture: "A vast square monastery of brick cells around a terraced, cruciform central shrine.",
    recognition: "UNESCO World Heritage Site (1985) — Ruins of the Buddhist Vihara at Paharpur",
    summary: "One of the great Buddhist monasteries of South Asia, built at Paharpur by the Pala king Dharmapala.",
    description: [
      "Rising from the plains of Naogaon, the central shrine of Paharpur still looks like the hill — pahar — that gave the village its name. Around it, 177 monastic cells once formed a square enclosure.",
      "Built under the Pala king Dharmapala in the late eighth century, Somapura was a centre of Buddhist learning for about three hundred years. Its terraces are lined with terracotta plaques showing everyday life, animals and deities.",
      "Its cruciform plan is thought to have influenced Buddhist architecture as far away as Myanmar and Java.",
    ],
    media: ["paharpur-aerial", "paharpur-vihara"],
  },
  {
    slug: "mahasthangarh",
    name: "Mahasthangarh",
    nameBn: "মহাস্থানগড়",
    region: "rajshahi",
    coordinates: [89.345, 24.9614],
    period: "From at least the 3rd century BCE",
    timeline: "pundranagara",
    architecture: "A fortified city of brick ramparts on the bank of the Karatoya, with temple mounds nearby.",
    summary: "The ruins of Pundranagara — the earliest urban archaeological site yet found in Bangladesh.",
    description: [
      "On the western bank of the Karatoya, north of Bogura, lie the ramparts of an ancient city. A Brahmi inscription found here points to a settlement in the Mauryan period, and the site stayed in use for well over a millennium.",
      "Mounds such as Govinda Bhita and the so-called Palace of Parshuram hold temples, residences and later additions. A site museum displays the terracotta, coins and sculpture found on the site.",
    ],
    media: ["mahasthangarh-parshuram", "mahasthangarh-govinda"],
  },
  {
    slug: "mainamati",
    name: "Mainamati & Shalban Vihara",
    nameBn: "ময়নামতি ও শালবন বিহার",
    region: "chattogram",
    coordinates: [91.1376, 23.4278],
    period: "7th–12th centuries CE",
    timeline: "mainamati",
    architecture: "Buddhist monasteries and stupas along the low Lalmai–Mainamati ridge.",
    summary: "A ridge of Buddhist monasteries near Cumilla, centred on the square courtyard of Shalban Vihara.",
    description: [
      "West of Cumilla, the low Lalmai–Mainamati ridge holds more than fifty sites from Bengal's Buddhist centuries. Shalban Vihara, the best known, is a square monastery of 115 cells around a central temple.",
      "Coins, copper plates and terracotta excavated here are displayed in the Mainamati museum beside the site.",
    ],
    media: ["shalban-vihara"],
  },
  {
    slug: "sixty-dome-mosque",
    name: "Sixty Dome Mosque",
    nameBn: "ষাট গম্বুজ মসজিদ",
    region: "khulna",
    coordinates: [89.7418, 22.6746],
    period: "15th century · Khan Jahan Ali",
    timeline: "bagerhat",
    architecture: "A brick hall of stone pillars roofed by rows of low domes, with corner towers.",
    recognition: "UNESCO World Heritage Site (1985) — Historic Mosque City of Bagerhat",
    summary: "The largest mosque of the Sultanate period in Bangladesh, at the heart of Khan Jahan Ali's mosque city.",
    description: [
      "In the fifteenth century the general and saint Khan Jahan Ali founded a city in the mangrove edge of the south-west. The Shat Gombuj Masjid is its grandest monument.",
      "Despite its name, the roof carries seventy-seven domes, supported on sixty stone pillars, with four towers at the corners. Around it, dozens of mosques, tombs and water tanks survive.",
    ],
    media: ["sixty-dome"],
  },
  {
    slug: "lalbagh-fort",
    name: "Lalbagh Fort",
    nameBn: "লালবাগ কেল্লা",
    region: "dhaka",
    coordinates: [90.3882, 23.719],
    city: "dhaka",
    period: "Begun 1678 · Mughal",
    timeline: "lalbagh",
    architecture: "An unfinished Mughal fort complex: a mosque, an audience hall and the Tomb of Pari Bibi.",
    summary: "A Mughal fortress in Old Dhaka that was never finished.",
    description: [
      "Prince Muhammad Azam, a son of the emperor Aurangzeb, began the fort in 1678 while governor of Bengal. His successor Shaista Khan continued it, but work stopped after the death of Shaista Khan's daughter, Pari Bibi, in 1684.",
      "Her tomb — clad in marble, black basalt and glazed tiles — stands at the centre of the complex, between the three-domed mosque and the Diwan-i-Aam.",
    ],
    media: ["lalbagh-pari-bibi", "lalbagh-kella", "lalbagh-1875"],
  },
  {
    slug: "kantajew-temple",
    name: "Kantajew Temple",
    nameBn: "কান্তজিউ মন্দির",
    region: "rangpur",
    coordinates: [88.669, 25.791],
    period: "Completed 1752",
    timeline: "kantajew",
    architecture: "A three-storey temple whose every surface is covered in terracotta panels.",
    summary: "A late-medieval temple in Dinajpur, famous for tens of thousands of terracotta tiles.",
    description: [
      "Begun by Maharaja Pran Nath of Dinajpur and completed by his son Ramnath in 1752, Kantajew Temple is a masterpiece of Bengal terracotta.",
      "Its panels tell stories from the Mahabharata and Ramayana alongside scenes of hunting, processions and daily life. The nine spires that once crowned it collapsed in the earthquake of 1897.",
    ],
    media: ["kantajew", "kantajew-terracotta"],
  },
  {
    slug: "ahsan-manzil",
    name: "Ahsan Manzil",
    nameBn: "আহসান মঞ্জিল",
    region: "dhaka",
    coordinates: [90.406, 23.7086],
    city: "dhaka",
    period: "Completed 1872",
    timeline: "ahsan-manzil",
    architecture: "An Indo-Saracenic palace with a tall central dome, facing the Buriganga.",
    summary: "The pink palace of the Nawabs of Dhaka, now a museum on the Buriganga.",
    description: [
      "Nawab Abdul Ghani completed the palace in 1872 and named it after his son, Khwaja Ahsanullah. It became the seat of the Dhaka Nawab family and a centre of the city's political life.",
      "A tornado in 1888 damaged the building badly; it was rebuilt with the dome that defines it today. Restored in the 1980s, it opened as a museum of the Bangladesh National Museum in 1992.",
    ],
    media: ["ahsan-manzil", "ahsan-manzil-1888"],
  },
  {
    slug: "panam-city",
    name: "Panam City",
    nameBn: "পানাম নগর",
    region: "dhaka",
    coordinates: [90.5985, 23.6435],
    period: "Late 19th – early 20th century",
    timeline: "sonargaon",
    architecture: "A single street of two- and three-storey merchant houses mixing European and Mughal details.",
    summary: "A ghost street of merchant mansions in Sonargaon, the old capital of eastern Bengal.",
    description: [
      "Sonargaon was a seat of power in medieval Bengal. In the colonial era, cloth merchants built a street of ornate houses at Panam, lined with canals.",
      "After 1947 many families left, and the houses stood empty. Today Panam is a protected site — a street of facades, arches and cast-iron balconies slowly weathering in the humid air.",
    ],
    media: ["panam-city", "panam-nogor"],
  },
  {
    slug: "curzon-hall",
    name: "Curzon Hall",
    nameBn: "কার্জন হল",
    region: "dhaka",
    coordinates: [90.4017, 23.7265],
    city: "dhaka",
    period: "Foundation 1904",
    timeline: "partition-1905",
    architecture: "Red brick with Mughal arches and domes — a blend of European and Mughal styles.",
    summary: "Built as a town hall for the new provincial capital; today the science faculty of the University of Dhaka.",
    description: [
      "Lord Curzon laid the foundation stone in 1904, on the eve of the 1905 partition of Bengal that made Dhaka a provincial capital. The hall later became part of the University of Dhaka, founded in 1921.",
      "Students gathered around it during the Language Movement of 1952, tying the building to the story of Bangla itself.",
    ],
    media: ["curzon-hall"],
  },
  {
    slug: "central-shaheed-minar",
    name: "Central Shaheed Minar",
    nameBn: "কেন্দ্রীয় শহীদ মিনার",
    region: "dhaka",
    coordinates: [90.3966, 23.7271],
    city: "dhaka",
    period: "Monument to 21 February 1952",
    timeline: "language-movement",
    architecture: "Abstract columns before a red sun — a mother and her martyred sons, in the design by Hamidur Rahman.",
    summary: "The monument to those killed defending the Bangla language on 21 February 1952.",
    description: [
      "On 21 February 1952 police opened fire on students in Dhaka demanding recognition of Bangla as a state language. The Shaheed Minar marks the place.",
      "Every year on 21 February people walk barefoot to the monument before dawn to lay flowers. Since 1999 the date has been observed worldwide as International Mother Language Day.",
    ],
    media: ["shaheed-minar"],
  },
  {
    slug: "national-parliament-house",
    name: "National Parliament House",
    nameBn: "জাতীয় সংসদ ভবন",
    region: "dhaka",
    coordinates: [90.3785, 23.7625],
    city: "dhaka",
    period: "Designed from 1961 · completed 1982",
    timeline: "parliament",
    architecture: "Louis Kahn's monumental concrete citadel of light, cut with geometric openings and set in water.",
    summary: "One of the landmarks of twentieth-century architecture, designed by Louis Kahn.",
    description: [
      "Commissioned in 1961, Louis Kahn's Jatiya Sangsad Bhaban was completed in 1982, years after the architect's death. Its concrete volumes, inlaid with white marble, are pierced by circles, triangles and rectangles that pull daylight deep inside.",
      "Set within an artificial lake, the building appears to float — a civic monument made of light, water and shadow.",
    ],
    media: ["parliament"],
  },
  {
    slug: "national-martyrs-memorial",
    name: "National Martyrs' Memorial",
    nameBn: "জাতীয় স্মৃতিসৌধ",
    region: "dhaka",
    coordinates: [90.2547, 23.9114],
    period: "Liberation War memorial",
    timeline: "independence",
    architecture: "Seven triangular concrete planes rising to a peak, designed by Syed Mainul Hossain.",
    summary: "The national monument at Savar to those who died in the Liberation War of 1971.",
    description: [
      "The Jatiyo Smriti Soudho at Savar honours those who died in the 1971 Liberation War. Its seven planes, rising in height, are often read as seven chapters of the struggle for independence.",
      "Visiting heads of state plant trees in its grounds, and on 16 December and 26 March the nation gathers here.",
    ],
    media: ["smriti-soudho"],
  },
];
