import type { NatureSpot } from "@/types/content";

export const nature: NatureSpot[] = [
  {
    slug: "sundarbans",
    name: "Sundarbans",
    nameBn: "সুন্দরবন",
    region: "khulna",
    coordinates: [89.45, 21.95],
    ecosystem: "mangrove",
    recognition: "UNESCO World Heritage Site (1997) · Ramsar Wetland (1992)",
    summary: "The largest mangrove forest on earth, a living tide-land shared by Bangladesh and India.",
    description: [
      "Where the Ganges, Brahmaputra and Meghna meet the Bay of Bengal, tides flood a labyrinth of channels and islands twice a day. The Sundarbans cover roughly ten thousand square kilometres, the larger part of it in Bangladesh.",
      "The forest takes its name, many say, from the sundari tree. Its mangroves breathe through roots that rise out of the mud, hold the coast together and blunt the force of cyclones.",
      "It is home to the Royal Bengal tiger, spotted deer, estuarine crocodiles, river dolphins and hundreds of bird species — and to the fishers, honey collectors and leaf gatherers who work its edges.",
    ],
    media: ["sundarbans-largest", "sundarbans-kachikhali", "sundarbans-tiger", "sundarbans-satellite"],
    ambient: "forest",
  },
  {
    slug: "coxs-bazar",
    name: "Cox's Bazar",
    nameBn: "কক্সবাজার",
    region: "chattogram",
    coordinates: [92.0058, 21.4272],
    ecosystem: "coast",
    summary: "An unbroken sandy shore of about 120 km, often called the longest natural sea beach in the world.",
    description: [
      "From Cox's Bazar town the beach runs south toward Teknaf almost without interruption. The Marine Drive follows the coast between the sea and green hills.",
      "Fishing boats launch from the sand at dawn; in the evening the whole town walks down to the water.",
    ],
    media: ["coxs-bazar", "coxs-bazar-dusk"],
    ambient: "sea",
  },
  {
    slug: "saint-martins-island",
    name: "Saint Martin's Island",
    nameBn: "সেন্ট মার্টিন দ্বীপ",
    region: "chattogram",
    coordinates: [92.323, 20.627],
    ecosystem: "island",
    summary: "Bangladesh's only coral island, in the north-eastern Bay of Bengal off Teknaf.",
    description: [
      "Known locally as Narikel Jinjira — 'coconut island' — Saint Martin's is a small island of coral rock, coconut palms and clear water. Its reefs and nesting beaches are fragile, and visitor numbers are regulated to protect them.",
    ],
    media: ["saint-martin", "saint-martin-blue"],
    ambient: "sea",
  },
  {
    slug: "ratargul-swamp-forest",
    name: "Ratargul Swamp Forest",
    nameBn: "রাতারগুল জলাবন",
    region: "sylhet",
    coordinates: [91.938, 25.01],
    ecosystem: "swamp-forest",
    summary: "A freshwater swamp forest near Sylhet whose trees stand in water through the monsoon.",
    description: [
      "In the rainy season the forest floor at Ratargul disappears under several metres of water, and the trees seem to grow straight out of a dark green lake. Visitors enter only by small boat, sliding between trunks.",
    ],
    media: ["ratargul"],
    ambient: "rain",
  },
  {
    slug: "sajek-valley",
    name: "Sajek Valley",
    nameBn: "সাজেক ভ্যালি",
    region: "chattogram",
    coordinates: [92.293, 23.382],
    ecosystem: "hills",
    summary: "A ridge-top in the Rangamati hills, known for seas of cloud at dawn.",
    description: [
      "High on a ridge near the Mizoram border, Sajek looks out over valleys that fill with cloud in the monsoon. The villages of the ridge belong to the Lushai, Pangkhua and Tripura communities.",
    ],
    media: ["sajek"],
    ambient: "forest",
  },
  {
    slug: "nilgiri-bandarban",
    name: "Bandarban & Nilgiri",
    nameBn: "বান্দরবান ও নীলগিরি",
    region: "chattogram",
    coordinates: [92.33, 21.99],
    ecosystem: "hills",
    summary: "The highest hills in the country, folded around the Sangu river.",
    description: [
      "Bandarban holds Bangladesh's highest peaks and its most rugged country. From viewpoints such as Nilgiri, ranges of green hills fade blue into the distance. The district is home to the Marma, Bawm, Mro and other communities.",
    ],
    media: ["nilgiri"],
    ambient: "forest",
  },
  {
    slug: "srimangal-tea-gardens",
    name: "Srimangal Tea Gardens",
    nameBn: "শ্রীমঙ্গলের চা বাগান",
    region: "sylhet",
    coordinates: [91.7296, 24.3065],
    ecosystem: "tea",
    summary: "The rolling tea estates of Moulvibazar, often called the tea capital of Bangladesh.",
    description: [
      "Around Srimangal, hills are combed into rows of tea bushes under the dappled shade of taller trees. Tea workers' communities, many descended from labourers brought in the colonial era, have tended these gardens for generations.",
      "Nearby Lawachara National Park shelters the western hoolock gibbon, the only ape found in Bangladesh.",
    ],
    media: ["tea-srimangal", "tea-malnicherra"],
    ambient: "rain",
  },
  {
    slug: "tanguar-haor",
    name: "Tanguar Haor",
    nameBn: "টাঙ্গুয়ার হাওর",
    region: "sylhet",
    coordinates: [91.07, 25.13],
    ecosystem: "wetland",
    recognition: "Ramsar Wetland of International Importance (2000)",
    summary: "A vast seasonal wetland in Sunamganj — an inland sea in the monsoon, a mosaic of pools in winter.",
    description: [
      "Haors are bowl-shaped floodplains that fill in the monsoon. Tanguar Haor, at the foot of the Meghalaya hills, becomes open water dotted with swamp trees and village mounds.",
      "In winter it is an important refuge for migratory waterbirds, and its fisheries support thousands of families.",
    ],
    media: ["tanguar-haor"],
    ambient: "river",
  },
  {
    slug: "jaflong",
    name: "Jaflong",
    nameBn: "জাফলং",
    region: "sylhet",
    coordinates: [92.017, 25.163],
    ecosystem: "river",
    summary: "Clear water and river stones where the hills of Meghalaya meet the plains.",
    description: [
      "At Jaflong the river descends from the Indian hills over beds of stone. Khasi villages, betel-leaf gardens and tea estates surround the valley.",
    ],
    media: ["jaflong"],
    ambient: "river",
  },
];
