import type { PersonStory } from "@/types/content";

/**
 * Editorial portraits of ways of life. They describe work and places, not named individuals —
 * replace with first-person interviews (with consent) before publication.
 */
export const people: PersonStory[] = [
  {
    slug: "farmer",
    role: "The Farmer",
    roleBn: "কৃষক",
    place: "Floodplains of the north and centre",
    region: "mymensingh",
    coordinates: [90.3, 24.6],
    theme: "work",
    summary: "Three rice seasons a year, timed to the rise and fall of the rivers.",
    story: "Rice is planted by the calendar of water: Aus before the monsoon, Aman in the flood season, Boro in the dry winter with irrigation. Silt left by the floods renews the soil each year — the same water that threatens also feeds.",
    media: "rice-field",
    editorial: true,
  },
  {
    slug: "fisher",
    role: "The Fisher",
    roleBn: "জেলে",
    place: "The Meghna estuary",
    region: "barishal",
    coordinates: [90.75, 22.6],
    theme: "work",
    summary: "Boats go out on the tide; the catch follows the season of the hilsa.",
    story: "On the lower Meghna, fishing families read tide, wind and season. When the hilsa run, whole villages work the nets; during spawning bans the boats stay ashore so the rivers can replenish.",
    media: "fishermen",
    editorial: true,
  },
  {
    slug: "weaver",
    role: "The Weaver",
    roleBn: "তাঁতি",
    place: "Rupganj, on the Sitalakhya",
    region: "dhaka",
    coordinates: [90.58, 23.79],
    theme: "craft",
    summary: "Patterns held in memory, inserted by hand, one weft at a time.",
    story: "A Jamdani weaver and apprentice share a pit loom. The master calls out the pattern; small bamboo shuttles of extra thread are laid in by hand. Nothing is drawn — the design lives in the weaver's head.",
    media: "jamdani-weaving",
    editorial: true,
  },
  {
    slug: "kantha-maker",
    role: "The Kantha Maker",
    roleBn: "কাঁথা শিল্পী",
    place: "Jamalpur & Jashore traditions",
    region: "mymensingh",
    coordinates: [89.95, 24.92],
    theme: "craft",
    summary: "Old saris, layered and stitched into new stories.",
    story: "Nakshi kantha began as a way to reuse worn cloth. Today many women's cooperatives turn it into income, while keeping the motifs — lotus, fish, the tree of life — that grandmothers stitched before them.",
    media: "nakshi-kantha-maker",
    editorial: true,
  },
  {
    slug: "potter",
    role: "The Potter",
    roleBn: "কুমার",
    place: "Bijoypur, Cumilla",
    region: "chattogram",
    coordinates: [91.17, 23.43],
    theme: "craft",
    summary: "River clay, a wheel, a kiln — and a craft older than the monasteries.",
    story: "In potter villages, clay is dug, cleaned and wedged by hand. Pots, lamps and figures dry in rows in the sun before firing. Alongside traditional vessels, workshops now make tableware and decor for city homes.",
    media: "potters",
    editorial: true,
  },
  {
    slug: "rickshaw-puller",
    role: "The Rickshaw Puller",
    roleBn: "রিকশাচালক",
    place: "Dhaka",
    region: "dhaka",
    coordinates: [90.41, 23.75],
    theme: "work",
    summary: "The city's most familiar journey, pedalled under painted panels.",
    story: "Many rickshaw pullers come to Dhaka from rural districts, sending earnings home. Their rickshaws — painted, tasselled, rented by the shift — are part of the city's daily choreography.",
    media: "rickshaw-wallah",
    editorial: true,
  },
  {
    slug: "student",
    role: "The Student",
    roleBn: "শিক্ষার্থী",
    place: "University of Dhaka",
    region: "dhaka",
    coordinates: [90.4017, 23.7265],
    theme: "learning",
    summary: "From the Language Movement to today, students have shaped the country's history.",
    story: "The campus around Curzon Hall has been the stage for many of the country's defining moments. Today's students study engineering, medicine, arts and computing — and carry the same sense that their generation can change the story.",
    media: "curzon-hall",
    editorial: true,
  },
  {
    slug: "commuter",
    role: "The Commuter",
    roleBn: "যাত্রী",
    place: "Dhaka Metro Rail",
    region: "dhaka",
    coordinates: [90.378, 23.78],
    theme: "ambition",
    summary: "A new rhythm for the capital, lifted above the traffic.",
    story: "Office workers, students and young professionals now cross the city on the elevated MRT Line 6. What once took hours in traffic becomes a ride of minutes — time given back for family, study and work.",
    media: "metro-uttara",
    editorial: true,
  },
  {
    slug: "tea-worker",
    role: "The Tea Worker",
    roleBn: "চা শ্রমিক",
    place: "Srimangal, Moulvibazar",
    region: "sylhet",
    coordinates: [91.73, 24.31],
    theme: "community",
    summary: "The hands behind every cup, in communities with their own languages and festivals.",
    story: "Tea-garden communities have lived and worked on the estates of Sylhet for generations. Plucking — 'two leaves and a bud' — is skilled, seasonal work, and the gardens' communities keep their own languages, songs and festivals.",
    media: "tea-srimangal",
    editorial: true,
  },
];
