import type { River } from "@/types/content";

/**
 * Major rivers. Courses come from content/geo (Natural Earth centerlines + schematic reaches,
 * see each river's `source` in geo.generated.json). Stops are real places along each river.
 */
export const rivers: River[] = [
  {
    slug: "padma",
    geoId: "padma",
    name: "Padma",
    nameBn: "পদ্মা",
    color: "#6fb7cf",
    course: "Enters from India near Chapai Nawabganj → Rajshahi → Hardinge Bridge → joins the Jamuna at Goalundo → Padma Bridge → meets the Meghna near Chandpur",
    summary: "The Ganges becomes the Padma as it enters Bangladesh, carrying Himalayan water across the western delta.",
    description: [
      "The Padma is the name of the Ganges in Bangladesh. It flows past Rajshahi, beneath the century-old Hardinge railway bridge, and gathers the Jamuna at Goalundo before sweeping south-east to join the Meghna near Chandpur.",
      "It is a restless river: its banks erode and its chars — sandbar islands — appear and vanish with each monsoon. The Padma Bridge, opened in June 2022, carries road and rail across it and ties the south-west to the capital.",
    ],
    stops: [
      { label: "Rajshahi", coordinates: [88.6042, 24.3745], note: "The city gathers on the embankment to watch the river at sunset.", media: "rajshahi-padma", ref: { kind: "city", slug: "rajshahi" } },
      { label: "Hardinge Bridge, Paksey", coordinates: [89.03, 24.07], note: "A steel railway bridge opened in 1915, still carrying trains across the Padma." },
      { label: "Goalundo–Daulatdia", coordinates: [89.76, 23.79], note: "Where the Jamuna joins the Padma; ferries have crossed here for generations.", media: "padma-daulatdia" },
      { label: "Padma Bridge", coordinates: [90.26, 23.45], note: "A 6.15 km road-and-rail bridge, opened on 25 June 2022.", media: "padma-bridge", ref: { kind: "destination", slug: "padma-bridge" } },
      { label: "Chandpur", coordinates: [90.65, 23.23], note: "The confluence with the Meghna — and the heart of hilsa country.", media: "hilsa", ref: { kind: "food", slug: "hilsa" } },
    ],
    cities: ["rajshahi"],
    media: ["padma-boatman", "padma-bridge-night", "padma-daulatdia"],
  },
  {
    slug: "jamuna",
    geoId: "jamuna",
    name: "Jamuna",
    nameBn: "যমুনা",
    color: "#9fd3e6",
    course: "Enters as the Brahmaputra in Kurigram → joined by the Teesta → Bahadurabad → Jamuna Bridge at Sirajganj → joins the Padma at Goalundo",
    summary: "The main channel of the Brahmaputra in Bangladesh — a vast braided river of shifting sandbars.",
    description: [
      "The Brahmaputra enters Bangladesh from Assam and, below Bahadurabad, flows south as the Jamuna. After the great floods of the late eighteenth century its main flow shifted west into this channel, leaving the Old Brahmaputra behind.",
      "The Jamuna is braided: many channels weave between chars, islands where millions of people farm and fish. The Jamuna Multipurpose Bridge, opened in 1998, finally joined the country's east and west by road and rail.",
    ],
    stops: [
      { label: "Chilmari, Kurigram", coordinates: [89.68, 25.56], note: "Near here the Teesta joins the Brahmaputra.", ref: { kind: "city", slug: "rangpur" } },
      { label: "Bahadurabad", coordinates: [89.7, 25.18], note: "The Old Brahmaputra branches away eastward toward Mymensingh." },
      { label: "Jamuna Bridge, Sirajganj", coordinates: [89.78, 24.4], note: "Opened in 1998, linking east and west.", media: "jamuna-from-bridge", ref: { kind: "destination", slug: "jamuna-bridge" } },
      { label: "Aricha–Goalundo", coordinates: [89.76, 23.82], note: "The Jamuna meets the Padma.", media: "padma-daulatdia" },
    ],
    cities: [],
    media: ["jamuna-from-bridge", "jamuna-bridge"],
  },
  {
    slug: "meghna",
    geoId: "meghna",
    name: "Meghna",
    nameBn: "মেঘনা",
    color: "#4b93bd",
    course: "Formed where the Surma and Kushiyara join → Bhairab → Chandpur, where it receives the Padma → Bhola → Bay of Bengal",
    summary: "Born in the north-eastern haors, the Meghna gathers the Padma and carries the delta's combined flow to the sea.",
    description: [
      "The Meghna begins in Sylhet where the Surma and Kushiyara — the two arms of the Barak — come together. Below Bhairab it becomes a great river, and at Chandpur it receives the Padma.",
      "From there the lower Meghna is one of the widest river mouths in the world, its estuary scattered with islands such as Bhola, Hatiya and Sandwip. The combined waters of the Ganges, Brahmaputra and Meghna reach the Bay of Bengal here.",
    ],
    stops: [
      { label: "Haor basin, Sylhet", coordinates: [91.25, 24.55], note: "Seasonal wetlands where the Surma and Kushiyara meet.", media: "tanguar-haor", ref: { kind: "nature", slug: "tanguar-haor" } },
      { label: "Bhairab", coordinates: [90.98, 24.02], note: "The Old Brahmaputra joins; road and rail bridges cross here." },
      { label: "Narsingdi", coordinates: [90.75, 23.9], note: "Wide water, sand barges and fishing boats.", media: "meghna-narsingdi" },
      { label: "Chandpur", coordinates: [90.65, 23.23], note: "The Padma joins the Meghna.", media: "hilsa-dhaka", ref: { kind: "food", slug: "hilsa" } },
      { label: "Bhola & the estuary", coordinates: [90.75, 22.6], note: "The largest island in the country sits in the river's mouth.", media: "fishermen" },
    ],
    cities: ["barishal"],
    media: ["meghna-narsingdi", "fishermen"],
  },
  {
    slug: "surma",
    geoId: "surma",
    name: "Surma",
    nameBn: "সুরমা",
    color: "#8fa6d6",
    course: "The Barak divides at Amalshid → Surma flows west past Sylhet and Sunamganj → joins the Kushiyara to form the Meghna",
    summary: "The river of Sylhet, flowing from the Barak past the city and into the haor country.",
    description: [
      "Where the Barak enters Bangladesh at Amalshid it splits in two: the Surma to the north and the Kushiyara to the south. The Surma flows past Sylhet, beneath the Keane Bridge, and on into the wetlands of Sunamganj before the two arms reunite as the Meghna.",
    ],
    stops: [
      { label: "Amalshid", coordinates: [92.48, 24.88], note: "The Barak divides into the Surma and Kushiyara." },
      { label: "Sylhet", coordinates: [91.8687, 24.8949], note: "The Keane Bridge crosses the Surma in the heart of the city.", media: "keane-bridge", ref: { kind: "city", slug: "sylhet" } },
      { label: "Sunamganj haors", coordinates: [91.4, 25.05], note: "Wetlands that become inland seas in the monsoon.", media: "tanguar-haor", ref: { kind: "nature", slug: "tanguar-haor" } },
    ],
    cities: ["sylhet"],
    media: ["surma", "keane-bridge"],
  },
  {
    slug: "teesta",
    geoId: "teesta",
    name: "Teesta",
    nameBn: "তিস্তা",
    color: "#7cc1b4",
    course: "From the Sikkim Himalaya → enters Bangladesh in Nilphamari → Teesta Barrage → joins the Brahmaputra in Kurigram",
    summary: "A Himalayan river that waters the northern plains of Rangpur before joining the Brahmaputra.",
    description: [
      "The Teesta rises in Sikkim, crosses the plains of North Bengal and enters Bangladesh in the north-west. The Teesta Barrage at Dalia diverts its water for irrigation in the dry season. It joins the Brahmaputra near Chilmari.",
    ],
    stops: [
      { label: "Teesta Barrage, Dalia", coordinates: [89.13, 26.18], note: "Irrigation barrage for the northern plains.", media: "teesta-barrage" },
      { label: "Rangpur plains", coordinates: [89.35, 25.85], note: "Farmland shaped by the river's floods and silt.", ref: { kind: "city", slug: "rangpur" } },
    ],
    cities: ["rangpur"],
    media: ["teesta-barrage"],
  },
  {
    slug: "old-brahmaputra",
    geoId: "old-brahmaputra",
    name: "Old Brahmaputra",
    nameBn: "পুরাতন ব্রহ্মপুত্র",
    color: "#7fa7c9",
    course: "Branches from the Jamuna near Bahadurabad → Jamalpur → Mymensingh → joins the Meghna at Bhairab",
    summary: "Once the main course of the Brahmaputra, now a quieter river through Mymensingh.",
    description: [
      "Until the late eighteenth century the Brahmaputra flowed south-east through Mymensingh to the Meghna. When its main flow moved west to the Jamuna, this older channel remained — a smaller river, but one that still defines the towns along its banks.",
    ],
    stops: [
      { label: "Jamalpur", coordinates: [89.95, 24.92], note: "A district town on the old channel." },
      { label: "Mymensingh", coordinates: [90.4203, 24.7471], note: "The riverside city of Shashi Lodge.", media: "shashi-lodge", ref: { kind: "city", slug: "mymensingh" } },
      { label: "Bhairab", coordinates: [90.98, 24.02], note: "The old river reaches the Meghna." },
    ],
    cities: ["mymensingh"],
    media: ["paddy"],
  },
  {
    slug: "karnaphuli",
    geoId: "karnaphuli",
    name: "Karnaphuli",
    nameBn: "কর্ণফুলী",
    color: "#5aa0c8",
    course: "From the Mizoram hills → Kaptai Lake → Chattogram port → Bay of Bengal at Patenga",
    summary: "The hill river that becomes the country's great harbour.",
    description: [
      "The Karnaphuli descends from the Mizoram hills into the Chittagong Hill Tracts, where the Kaptai dam, completed in the early 1960s, created Kaptai Lake. Downstream it becomes the harbour of Chattogram before meeting the sea at Patenga.",
    ],
    stops: [
      { label: "Kaptai Lake", coordinates: [92.2, 22.6], note: "A reservoir among the hills of Rangamati.", media: "sajek" },
      { label: "Chattogram port", coordinates: [91.8, 22.31], note: "Ships line the river's final reach.", media: "karnaphuli-night", ref: { kind: "city", slug: "chattogram" } },
    ],
    cities: ["chattogram"],
    media: ["karnaphuli-night"],
  },
  {
    slug: "pasur",
    geoId: "pasur",
    name: "Rupsha–Pasur",
    nameBn: "রূপসা–পশুর",
    color: "#3f86ad",
    course: "Rupsha at Khulna → Pasur past Mongla → through the Sundarbans to the Bay of Bengal",
    summary: "The tidal river that carries Khulna's traffic through the mangroves to the sea.",
    description: [
      "At Khulna the Rupsha flows beneath the Rupsha Bridge; downstream it becomes the Pasur, passes Mongla port and cuts through the Sundarbans to the Bay of Bengal. Its water rises and falls with the tide twice a day.",
    ],
    stops: [
      { label: "Khulna", coordinates: [89.5403, 22.8456], note: "The Rupsha Bridge spans the river.", media: "rupsha-bridge", ref: { kind: "city", slug: "khulna" } },
      { label: "Mongla", coordinates: [89.6, 22.48], note: "The country's second seaport, on the edge of the forest." },
      { label: "Sundarbans", coordinates: [89.6, 22.05], note: "Tidal channels branch into the mangroves.", media: "sundarbans-largest", ref: { kind: "nature", slug: "sundarbans" } },
    ],
    cities: ["khulna"],
    media: ["rupsha-bridge", "sundarbans-largest"],
  },
  {
    slug: "buriganga",
    geoId: "buriganga",
    name: "Buriganga",
    nameBn: "বুড়িগঙ্গা",
    color: "#d08a5a",
    course: "Flows along the southern edge of Old Dhaka → joins the Dhaleshwari",
    summary: "Old Dhaka's river — the reason the capital is where it is.",
    description: [
      "The Buriganga runs along the southern edge of Old Dhaka. Sadarghat, one of the busiest river terminals in the world, sits on its bank, as does Ahsan Manzil. Cleaning and reviving it is one of the city's long-running environmental challenges.",
    ],
    stops: [
      { label: "Sadarghat", coordinates: [90.41, 23.705], note: "Launches depart for the southern delta.", media: "boats" },
      { label: "Ahsan Manzil", coordinates: [90.406, 23.7086], note: "The Nawabs' palace faces the river.", media: "ahsan-manzil", ref: { kind: "heritage", slug: "ahsan-manzil" } },
    ],
    cities: ["dhaka"],
    media: ["boats", "ahsan-manzil"],
  },
];
