import type { TimelineEvent } from "@/types/content";

/**
 * Time-travel timeline. Years are CE; negative numbers are BCE.
 * Each era carries its own atmosphere (palette + typographic voice) used by the timeline chapter.
 */
const ANCIENT = { bg: "#2a1d14", ink: "#f0e2c8", accent: "#c8793f" };
const SULTANATE = { bg: "#1c2620", ink: "#efe6d2", accent: "#b99b55" };
const MUGHAL = { bg: "#2b1618", ink: "#f4e7d7", accent: "#c4574a" };
const COLONIAL = { bg: "#1b2129", ink: "#e9e4da", accent: "#9fb3c8" };
const NATION = { bg: "#141414", ink: "#f3ede1", accent: "#c0392b" };
const NOW = { bg: "#0f2330", ink: "#eef3f2", accent: "#5fb3c9" };

export const timeline: TimelineEvent[] = [
  {
    slug: "pundranagara",
    year: -300,
    yearLabel: "3rd c. BCE",
    era: "Ancient Bengal",
    title: "Pundranagara",
    place: "Mahasthangarh, Bogura",
    coordinates: [89.345, 24.9614],
    event: "A fortified city stands on the Karatoya.",
    context: "A Brahmi inscription found at Mahasthangarh points to an urban centre in the Mauryan period — the earliest city yet found in Bangladesh.",
    media: "mahasthangarh-parshuram",
    ref: { kind: "heritage", slug: "mahasthangarh" },
    palette: ANCIENT,
    type: "ancient",
  },
  {
    slug: "mainamati",
    year: 700,
    yearLabel: "7th–12th c.",
    era: "Buddhist kingdoms",
    title: "Monasteries of Mainamati",
    place: "Cumilla",
    coordinates: [91.1376, 23.4278],
    event: "Monasteries rise along the Lalmai–Mainamati ridge.",
    context: "The Deva and Chandra dynasties of south-eastern Bengal patronise Buddhist learning; Shalban Vihara is among the monasteries built on the ridge.",
    media: "shalban-vihara",
    ref: { kind: "heritage", slug: "mainamati" },
    palette: ANCIENT,
    type: "ancient",
  },
  {
    slug: "somapura",
    year: 790,
    yearLabel: "Late 8th c.",
    era: "Pala Empire",
    title: "Somapura Mahavihara",
    place: "Paharpur, Naogaon",
    coordinates: [88.9769, 25.0311],
    event: "The Pala king Dharmapala builds a great monastery.",
    context: "Somapura becomes one of the largest Buddhist monasteries south of the Himalayas and a centre of learning for three centuries.",
    media: "paharpur-aerial",
    ref: { kind: "heritage", slug: "somapura-mahavihara" },
    palette: ANCIENT,
    type: "ancient",
  },
  {
    slug: "sultanate",
    year: 1352,
    yearLabel: "1352",
    era: "Bengal Sultanate",
    title: "Bengal united",
    place: "Sonargaon & the delta",
    coordinates: [90.6, 23.65],
    event: "Shamsuddin Ilyas Shah unites the regions of Bengal into one sultanate.",
    context: "For nearly two centuries the independent Bengal Sultanate trades across the Indian Ocean; Sonargaon is one of its great centres.",
    media: "panam-city",
    ref: { kind: "heritage", slug: "panam-city" },
    palette: SULTANATE,
    type: "sultanate",
  },
  {
    slug: "bagerhat",
    year: 1450,
    yearLabel: "15th c.",
    era: "Bengal Sultanate",
    title: "The Mosque City of Bagerhat",
    place: "Bagerhat, Khulna",
    coordinates: [89.7418, 22.6746],
    event: "Khan Jahan Ali founds a city at the edge of the mangroves.",
    context: "The Sixty Dome Mosque anchors a city of mosques, tombs, roads and water tanks carved out of the forest.",
    media: "sixty-dome",
    ref: { kind: "heritage", slug: "sixty-dome-mosque" },
    palette: SULTANATE,
    type: "sultanate",
  },
  {
    slug: "dhaka-capital",
    year: 1610,
    yearLabel: "1610",
    era: "Mughal Bengal",
    title: "Jahangirnagar",
    place: "Dhaka",
    coordinates: [90.4, 23.715],
    event: "Islam Khan makes Dhaka the Mughal capital of Bengal.",
    context: "Renamed Jahangirnagar, the city on the Buriganga becomes a centre of administration and of the muslin trade.",
    media: "lalbagh-kella",
    ref: { kind: "city", slug: "dhaka" },
    palette: MUGHAL,
    type: "mughal",
  },
  {
    slug: "lalbagh",
    year: 1678,
    yearLabel: "1678",
    era: "Mughal Bengal",
    title: "Lalbagh Fort",
    place: "Old Dhaka",
    coordinates: [90.3882, 23.719],
    event: "Prince Muhammad Azam begins a fort on the Buriganga.",
    context: "Continued by Shaista Khan, the fort is abandoned after the death of his daughter Pari Bibi in 1684 — and remains unfinished to this day.",
    media: "lalbagh-pari-bibi",
    ref: { kind: "heritage", slug: "lalbagh-fort" },
    palette: MUGHAL,
    type: "mughal",
  },
  {
    slug: "kantajew",
    year: 1752,
    yearLabel: "1752",
    era: "Late Mughal Bengal",
    title: "Kantajew Temple",
    place: "Dinajpur",
    coordinates: [88.669, 25.791],
    event: "Maharaja Ramnath completes a temple clad in terracotta.",
    context: "Thousands of hand-made terracotta panels tell epics and everyday life in fired river clay.",
    media: "kantajew",
    ref: { kind: "heritage", slug: "kantajew-temple" },
    palette: MUGHAL,
    type: "mughal",
  },
  {
    slug: "plassey",
    year: 1757,
    yearLabel: "1757",
    era: "Company rule",
    title: "Palashi",
    place: "Palashi (today West Bengal, India)",
    coordinates: [88.25, 23.8],
    event: "The East India Company defeats Nawab Siraj-ud-Daulah.",
    context: "The Battle of Plassey opens nearly two centuries of British rule over Bengal.",
    media: "lalbagh-1875",
    palette: COLONIAL,
    type: "colonial",
  },
  {
    slug: "ahsan-manzil",
    year: 1872,
    yearLabel: "1872",
    era: "British India",
    title: "Ahsan Manzil",
    place: "Dhaka, on the Buriganga",
    coordinates: [90.406, 23.7086],
    event: "Nawab Abdul Ghani completes the pink palace.",
    context: "The seat of the Dhaka Nawab family becomes a centre of the city's political life; a tornado in 1888 forces its rebuilding.",
    media: "ahsan-manzil-1888",
    ref: { kind: "heritage", slug: "ahsan-manzil" },
    palette: COLONIAL,
    type: "colonial",
  },
  {
    slug: "partition-1905",
    year: 1905,
    yearLabel: "1905",
    era: "British India",
    title: "Partition of Bengal",
    place: "Dhaka",
    coordinates: [90.4017, 23.7265],
    event: "Dhaka becomes capital of the new province of Eastern Bengal and Assam.",
    context: "Curzon Hall is raised as a town hall for the new capital. The partition is annulled in 1911; the University of Dhaka follows in 1921.",
    media: "curzon-hall",
    ref: { kind: "heritage", slug: "curzon-hall" },
    palette: COLONIAL,
    type: "colonial",
  },
  {
    slug: "partition-1947",
    year: 1947,
    yearLabel: "1947",
    era: "Pakistan period",
    title: "East Bengal",
    place: "The delta, divided",
    coordinates: [90.4, 23.8],
    event: "British India is partitioned; East Bengal becomes part of Pakistan.",
    context: "Separated from West Pakistan by more than 1,500 km of India, the province is renamed East Pakistan in 1955.",
    media: "boats",
    palette: COLONIAL,
    type: "colonial",
  },
  {
    slug: "language-movement",
    year: 1952,
    yearLabel: "21 Feb 1952",
    era: "Pakistan period",
    title: "The Language Movement",
    place: "Dhaka University area",
    coordinates: [90.3966, 23.7271],
    event: "Police fire on students demanding recognition of Bangla.",
    context: "The martyrs of 21 February make the language the foundation of a new national identity. The Shaheed Minar marks the place.",
    media: "language-movement-1952",
    ref: { kind: "heritage", slug: "central-shaheed-minar" },
    palette: NATION,
    type: "nation",
  },
  {
    slug: "independence",
    year: 1971,
    yearLabel: "1971",
    era: "Liberation War",
    title: "Independence",
    place: "Bangladesh",
    coordinates: [90.2547, 23.9114],
    event: "Independence is declared on 26 March; victory comes on 16 December.",
    context: "After nine months of war the People's Republic of Bangladesh is born. The National Martyrs' Memorial at Savar honours those who died.",
    media: "smriti-soudho",
    ref: { kind: "heritage", slug: "national-martyrs-memorial" },
    palette: NATION,
    type: "nation",
  },
  {
    slug: "parliament",
    year: 1982,
    yearLabel: "1982",
    era: "Bangladesh",
    title: "A house of light",
    place: "Sher-e-Bangla Nagar, Dhaka",
    coordinates: [90.3785, 23.7625],
    event: "Louis Kahn's National Parliament House is completed.",
    context: "Begun in the 1960s, the building becomes a landmark of modern architecture.",
    media: "parliament",
    ref: { kind: "heritage", slug: "national-parliament-house" },
    palette: NATION,
    type: "nation",
  },
  {
    slug: "sundarbans-unesco",
    year: 1997,
    yearLabel: "1997",
    era: "Bangladesh",
    title: "The Sundarbans on the World Heritage List",
    place: "Khulna division",
    coordinates: [89.45, 21.95],
    event: "UNESCO inscribes the Sundarbans of Bangladesh.",
    context: "It joins Paharpur and the Mosque City of Bagerhat, both inscribed in 1985.",
    media: "sundarbans-largest",
    ref: { kind: "nature", slug: "sundarbans" },
    palette: NOW,
    type: "contemporary",
  },
  {
    slug: "mother-language-day",
    year: 1999,
    yearLabel: "1999",
    era: "Bangladesh",
    title: "International Mother Language Day",
    place: "UNESCO, Paris",
    coordinates: [90.3966, 23.7271],
    event: "UNESCO proclaims 21 February International Mother Language Day.",
    context: "The day first marked in Dhaka's streets becomes a day for every language in the world.",
    media: "shaheed-minar",
    ref: { kind: "culture", slug: "bangla-language" },
    palette: NOW,
    type: "contemporary",
  },
  {
    slug: "padma-bridge",
    year: 2022,
    yearLabel: "2022",
    era: "Bangladesh",
    title: "Across the Padma",
    place: "Mawa–Janjira",
    coordinates: [90.26, 23.45],
    event: "The Padma Bridge opens in June; Dhaka's metro follows in December.",
    context: "The 6.15 km road-and-rail bridge links the south-west to the capital; MRT Line 6 begins service on 28 December.",
    media: "padma-bridge",
    ref: { kind: "destination", slug: "padma-bridge" },
    palette: NOW,
    type: "contemporary",
  },
];
