/**
 * Generates Framer page components (framer/pages/*.tsx) from the Next.js
 * pages, so a Framer project gets exactly the same compositions and content.
 *
 * Each Next page is rendered to its element tree; every top-level section
 * element becomes `{ name, props }`. Pages with a [slug] get one entry per
 * slug behind an Enum property control. Local media paths become absolute
 * URLs and the Next-only API endpoint is dropped (the form falls back to
 * email in Framer).
 *
 *   npx tsx scripts/framer-pages.mts
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { isValidElement, type ReactElement, type ReactNode } from "react";
import * as Sections from "../components/sections";
import { getArticles, getProjects } from "../lib/cms";
import { legalPages } from "../content/studio";

const MEDIA = "https://raw.githubusercontent.com/uxuimonir/2nd/83430dfd2a7c2050799516849c47d8f2be688dc7/noire/public/media/";
const OUT = path.join(import.meta.dirname, "..", "framer", "pages");
/** Module URLs of the section code files in the Framer project (framer/modules.json). */
const MODULES: Record<string, string> = JSON.parse(readFileSync(path.join(import.meta.dirname, "..", "framer", "modules.json"), "utf8"));

const names = new Map<unknown, string>(Object.entries(Sections).map(([k, v]) => [v, k]));

type Section = { name: string; props: Record<string, unknown> };

function flatten(node: ReactNode): ReactElement[] {
  if (Array.isArray(node)) return node.flatMap(flatten);
  if (!isValidElement(node)) return [];
  const name = names.get(node.type);
  if (name) return [node];
  return flatten((node.props as { children?: ReactNode }).children);
}

function clean(value: unknown): unknown {
  if (typeof value === "string") {
    if (value.startsWith("/media/")) return MEDIA + value.slice("/media/".length);
    if (value.startsWith("/legal/")) return "/" + value.slice("/legal/".length);
    return value.replaceAll("[img] /media/", "[img] " + MEDIA);
  }
  if (Array.isArray(value)) return value.map(clean);
  if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, clean(v)]));
  return value;
}

async function render(load: () => Promise<{ default: (p: any) => unknown }>, params?: Record<string, string>): Promise<Section[]> {
  const mod = await load();
  const tree = (await mod.default(params ? { params: Promise.resolve(params), searchParams: Promise.resolve({}) } : {})) as ReactNode;
  return flatten(tree).map((el) => {
    const props = { ...(el.props as Record<string, unknown>) };
    delete props.children;
    if (names.get(el.type) === "NoireContact") props.endpoint = "";
    return { name: names.get(el.type)!, props: clean(props) as Record<string, unknown> };
  });
}

function write(component: string, pages: Record<string, Section[]>, doc: string) {
  const keys = Object.keys(pages);
  const used = [...new Set(Object.values(pages).flatMap((s) => s.map((x) => x.name)))].sort();
  const multi = keys.length > 1;
  const src = `// NOIRÉ 2 — ${doc}
// Generated by scripts/framer-pages.mts from the Next.js pages — edit content
// there (content/*.ts) and regenerate, or edit the props here directly.
import { addPropertyControls, ControlType } from "framer"
import type { CSSProperties } from "react"
// Section code files, imported by their Framer module URL (untyped, hence ts-ignore).
${used.map((n) => `// @ts-ignore\nimport ${n} from "${MODULES[n]}"`).join("\n")}

const C: Record<string, any> = { ${used.join(", ")} }

const PAGES: Record<string, { name: string; props: Record<string, any> }[]> = ${JSON.stringify(pages)}

/**
 * @framerSupportedLayoutWidth fixed
 * @framerSupportedLayoutHeight auto
 * @framerIntrinsicWidth 1440
 */
export default function ${component}(props: { page?: string; style?: CSSProperties }) {
    const sections = PAGES[props.page ?? "${keys[0]}"] ?? PAGES["${keys[0]}"]
    return (
        <div style={{ ...props.style, width: "100%", display: "flex", flexDirection: "column" }}>
            {sections.map((s, i) => {
                const Section = C[s.name]
                return <Section key={i} {...s.props} />
            })}
        </div>
    )
}

addPropertyControls(${component}, {
    ${multi ? `page: { type: ControlType.Enum, title: "Page", options: ${JSON.stringify(keys)}, defaultValue: "${keys[0]}" },` : ""}
})
`;
  writeFileSync(path.join(OUT, `${component}.tsx`), src);
  console.log(`${component}.tsx  ${(src.length / 1024).toFixed(1)} KB  [${keys.join(", ")}]`);
}

mkdirSync(OUT, { recursive: true });

const single = async (file: string) => ({ main: await render(() => import(`../app/${file}`)) });
const each = async (file: string, slugs: string[]) => Object.fromEntries(await Promise.all(slugs.map(async (slug) => [slug, await render(() => import(`../app/${file}`), { slug })])));

write("NoireAboutPage", await single("about/page.tsx"), "About page");
write("NoireServicesPage", await single("services/page.tsx"), "Services page");
write("NoireJournalPage", await single("journal/page.tsx"), "Journal index page");
write("NoireContactPage", await single("contact/page.tsx"), "Contact page");
write("NoireStudioPage", await single("studio/page.tsx"), "Studio / Archive page");
write("NoireRecognitionPage", await single("recognition/page.tsx"), "Recognition page");
write("NoireColophonPage", await single("colophon/page.tsx"), "Colophon page");
write("NoireLegalPage", await each("legal/[slug]/page.tsx", legalPages.map((p) => p.slug)), "Privacy / Terms pages");
write("NoireProjectPage", await each("work/[slug]/page.tsx", getProjects().map((p) => p.slug)), "Project detail pages (one per project)");
write("NoireArticlePage", await each("journal/[slug]/page.tsx", getArticles().map((a) => a.slug)), "Journal article pages (one per article)");
