import type { Project } from "@/lib/types";

/**
 * Projects collection. All projects, clients and collaborators are fictional
 * demo content. Image ids resolve through content/media.ts.
 */
export const projects: Project[] = [
  {
    title: "Quiet Matter",
    slug: "quiet-matter",
    client: "Halde Kunsthalle",
    year: 2026,
    category: "Exhibition",
    discipline: "Exhibition identity & catalogue",
    location: "Bergen",
    thesis: "An exhibition about weight, told almost entirely through restraint.",
    shortDescription:
      "Identity, wayfinding and catalogue for a survey of post-war stone sculpture.",
    longDescription: [
      "Quiet Matter gathered forty sculptures made between 1948 and 1979, most of them carved rather than cast. The curators wanted visitors to slow down before they read anything — to register mass, grain and shadow first.",
      "We built the identity around that delay. Wall texts sit low and small, set in a single weight. Titles are placed at the height of a plinth rather than at eye level, so reading happens in the same posture as looking. The catalogue follows the same logic: full-bleed plates first, captions gathered at the back.",
    ],
    heroImage: "p-quiet-matter-hero",
    heroFocal: "50% 55%",
    gallery: [
      {
        image: "p-quiet-matter-01",
        caption: "Main hall, plinth heights set to the reading line.",
        layout: "full",
      },
      {
        image: "p-quiet-matter-02",
        caption: "Pair of forms, catalogue plate 12.",
        layout: "portrait",
      },
      { image: "p-quiet-matter-03", caption: "Surface study used for the cover.", layout: "inset" },
      {
        image: "p-quiet-matter-04",
        caption: "Room four: works on paper hung at 1.1 m.",
        layout: "wide",
      },
      { image: "p-quiet-matter-05", caption: "Low plinths, west gallery.", layout: "pair" },
      {
        image: "p-quiet-matter-06",
        caption: "Study of a single form in raking light.",
        layout: "pair",
      },
    ],
    role: "Identity, exhibition graphics, catalogue design",
    team: ["Mira Solberg", "Jonas Erde", "Lea Okafor"],
    deliverables: [
      "Visual identity",
      "Wayfinding & wall texts",
      "Exhibition catalogue, 224 pp.",
      "Poster series",
    ],
    credits: [
      { role: "Curation", name: "Halde Kunsthalle (fictional)" },
      { role: "Exhibition architecture", name: "Studio Vetle" },
      { role: "Printing", name: "Grå Trykk" },
    ],
    outcome:
      "Visitors stayed an average of 74 minutes — the longest dwell time recorded for a survey show at the venue (demo figure).",
    featured: true,
    sortOrder: 1,
    related: ["index-of-rooms", "ninefold"],
  },
  {
    title: "Tidewater",
    slug: "tidewater",
    client: "Baía Baths",
    year: 2025,
    category: "Spatial",
    discipline: "Spatial identity & signage",
    location: "Porto",
    thesis: "A bathhouse identity that lets the water and the tile do the talking.",
    shortDescription:
      "Spatial identity, signage and tile system for a restored 1930s seawater bathhouse.",
    longDescription: [
      "Baía Baths reopened after eleven years behind scaffolding. The building already had a voice — green-glazed tile, a vaulted pool hall and a long window onto the Atlantic — and the brief was to add as little as possible.",
      "The signage is fired into tile rather than mounted on it, using a custom stencil alphabet derived from the original pool-depth numerals. Colour comes only from the glaze; print matter follows the same two greens and a sea-washed white.",
    ],
    heroImage: "p-tidewater-hero",
    heroFocal: "50% 60%",
    gallery: [
      {
        image: "p-tidewater-01",
        caption: "Pool hall, late afternoon through the arched window.",
        layout: "full",
      },
      { image: "p-tidewater-02", caption: "Glazed tile field, changing rooms.", layout: "pair" },
      { image: "p-tidewater-03", caption: "Caustic light on the pool floor.", layout: "pair" },
      { image: "p-tidewater-04", caption: "Fired depth marker, 1.40 m.", layout: "inset" },
      { image: "p-tidewater-05", caption: "View from the outdoor deck.", layout: "wide" },
    ],
    role: "Spatial identity, signage, tile design",
    team: ["Mira Solberg", "Tomás Vale"],
    deliverables: ["Stencil typeface", "Fired-tile signage", "Printed matter", "Seasonal posters"],
    credits: [
      { role: "Architecture", name: "Atelier Rocha Lima" },
      { role: "Ceramics", name: "Fábrica Azul" },
    ],
    outcome: "Shortlisted for a regional heritage-reuse prize (demo recognition).",
    featured: true,
    sortOrder: 2,
    related: ["the-long-table", "index-of-rooms"],
  },
  {
    title: "Ninefold",
    slug: "ninefold",
    client: "Ferro Editions",
    year: 2025,
    category: "Editorial",
    discipline: "Book design",
    location: "Milan",
    thesis: "Nine essays, nine folds — a book whose structure is its argument.",
    shortDescription:
      "Design and production of an essay collection printed on a single folded sheet per chapter.",
    longDescription: [
      "Ninefold collects nine essays on making things slowly. Each essay is printed on one large sheet, folded and sewn, so every chapter is physically a single object before it is part of a book.",
      "The typography is deliberately plain: one serif, one size for text, generous margins on the fold side. The only colour is a vermilion thread that runs through the binding and surfaces as a single rule on each opening spread.",
    ],
    heroImage: "p-ninefold-hero",
    heroFocal: "50% 50%",
    gallery: [
      { image: "p-ninefold-01", caption: "Opening spread, essay three.", layout: "wide" },
      { image: "p-ninefold-02", caption: "The full edition, stacked.", layout: "portrait" },
      { image: "p-ninefold-03", caption: "A single folded sheet before sewing.", layout: "inset" },
      { image: "p-ninefold-04", caption: "Typesetting detail, 10.5/15 pt.", layout: "pair" },
      { image: "p-ninefold-05", caption: "Fore-edge, uncut.", layout: "pair" },
      { image: "p-ninefold-06", caption: "Cover family, nine colourways.", layout: "full" },
    ],
    role: "Book design, typography, production",
    team: ["Mira Solberg", "Lea Okafor"],
    deliverables: ["Book design, 9 × 32 pp.", "Cover system", "Launch invitation"],
    credits: [
      { role: "Editor", name: "Ferro Editions (fictional)" },
      { role: "Binding", name: "Legatoria Sesto" },
    ],
    featured: true,
    sortOrder: 3,
    related: ["paper-weather", "quiet-matter"],
  },
  {
    title: "Lowlight",
    slug: "lowlight",
    client: "Atelier Ombra",
    year: 2024,
    category: "Art Direction",
    discipline: "Art direction & campaign",
    location: "Copenhagen",
    thesis: "Photographing lamps by the light they give, not the way they look.",
    shortDescription:
      "Art direction for a lighting maker's first collection — shot entirely after dark.",
    longDescription: [
      "Atelier Ombra makes small runs of hand-spun lamps. Product photography usually flattens them into silhouettes on white. We proposed the opposite: shoot each lamp in a real room at night, lit only by itself.",
      "The resulting campaign is mostly shadow. Product information moves to quiet captions and a printed index, so the images can stay unretouched and atmospheric.",
    ],
    heroImage: "p-lowlight-hero",
    heroFocal: "50% 40%",
    gallery: [
      { image: "p-lowlight-01", caption: "Dome pendant, kitchen, 11 pm.", layout: "portrait" },
      { image: "p-lowlight-02", caption: "Wall wash study.", layout: "full" },
      { image: "p-lowlight-03", caption: "Opal globe, detail.", layout: "inset" },
      { image: "p-lowlight-04", caption: "Collection in sequence.", layout: "wide" },
      { image: "p-lowlight-05", caption: "Cast shadow, hallway.", layout: "pair" },
      { image: "p-lowlight-06", caption: "Index plate, table lamp no. 4.", layout: "pair" },
    ],
    role: "Art direction, campaign, catalogue",
    team: ["Mira Solberg", "Jonas Erde"],
    deliverables: [
      "Campaign photography direction",
      "Product index",
      "Catalogue",
      "Website imagery",
    ],
    credits: [
      { role: "Photography", name: "Ida Strøm" },
      { role: "Set", name: "Noiré" },
    ],
    featured: false,
    sortOrder: 4,
    related: ["quiet-matter", "field-notes-on-clay"],
  },
  {
    title: "Field Notes on Clay",
    slug: "field-notes-on-clay",
    client: "Kiln Room",
    year: 2024,
    category: "Identity",
    discipline: "Brand identity",
    location: "Kyoto",
    thesis: "An identity that is fired, not printed — and changes a little every batch.",
    shortDescription:
      "Identity for a ceramics studio, built from glaze tests and the marks left by the kiln.",
    longDescription: [
      "Kiln Room is a two-person ceramics studio that sells a small number of pieces each season. Their old logo was a vector drawing of a pot. They wanted something closer to how they actually work.",
      "The new mark is stamped into every piece by hand, and the printed version is scanned from those stamps each season — so the identity drifts slightly over time, the way a glaze does. Colour comes from a palette of eleven test tiles.",
    ],
    heroImage: "p-field-notes-on-clay-hero",
    heroFocal: "50% 55%",
    gallery: [
      {
        image: "p-field-notes-on-clay-01",
        caption: "Shelf of spring-batch vessels.",
        layout: "wide",
      },
      { image: "p-field-notes-on-clay-02", caption: "Glaze test, ash over iron.", layout: "inset" },
      { image: "p-field-notes-on-clay-03", caption: "Pair, unglazed and glazed.", layout: "full" },
      { image: "p-field-notes-on-clay-04", caption: "Bowl from above.", layout: "pair" },
      { image: "p-field-notes-on-clay-05", caption: "Tall jar, studio window.", layout: "pair" },
      {
        image: "p-field-notes-on-clay-06",
        caption: "Stamped base, season three.",
        layout: "portrait",
      },
    ],
    role: "Identity, packaging, seasonal catalogue",
    team: ["Mira Solberg", "Tomás Vale"],
    deliverables: ["Stamp identity", "Packaging", "Seasonal price list", "Web shop direction"],
    credits: [{ role: "Ceramics", name: "Kiln Room (fictional)" }],
    featured: false,
    sortOrder: 5,
    related: ["lowlight", "the-long-table"],
  },
  {
    title: "Index of Rooms",
    slug: "index-of-rooms",
    client: "Marrow Architects",
    year: 2023,
    category: "Digital",
    discipline: "Digital archive & website",
    location: "Rotterdam",
    thesis: "A practice archive organised by rooms, not by buildings.",
    shortDescription:
      "Website and digital archive for an architecture practice, indexed by the rooms they have made.",
    longDescription: [
      "Marrow had thirty years of projects and no coherent archive. Instead of a portfolio of buildings, we proposed an index of rooms: every stair, corridor, kitchen and courtyard they had drawn, tagged and searchable.",
      "The site is built like a card catalogue. A dense text index sits beside a single large image, and each room links back to its building, its year and its drawings. It is fast, keyboard-friendly and has no carousel anywhere.",
    ],
    heroImage: "p-index-of-rooms-hero",
    heroFocal: "40% 50%",
    gallery: [
      {
        image: "p-index-of-rooms-01",
        caption: "Corridor, Sint-Jan housing, 2009.",
        layout: "full",
      },
      { image: "p-index-of-rooms-02", caption: "Stair, school extension.", layout: "portrait" },
      { image: "p-index-of-rooms-03", caption: "Facade grid, archive entry 0412.", layout: "pair" },
      { image: "p-index-of-rooms-04", caption: "Opening, reading room.", layout: "pair" },
      {
        image: "p-index-of-rooms-05",
        caption: "Plan drawing, redrawn for the index.",
        layout: "wide",
      },
      { image: "p-index-of-rooms-06", caption: "Column shadows, market hall.", layout: "inset" },
    ],
    role: "Information architecture, design, development direction",
    team: ["Mira Solberg", "Jonas Erde", "Lea Okafor"],
    deliverables: ["Archive taxonomy", "Website design", "Image guidelines", "Editorial templates"],
    credits: [{ role: "Development", name: "Kade Digital" }],
    featured: false,
    sortOrder: 6,
    related: ["quiet-matter", "tidewater"],
  },
  {
    title: "The Long Table",
    slug: "the-long-table",
    client: "Sobremesa",
    year: 2023,
    category: "Identity",
    discipline: "Restaurant identity",
    location: "Lisbon",
    thesis: "A restaurant identity designed for the hour after the meal.",
    shortDescription:
      "Identity, menus and table objects for a single-table restaurant serving one sitting a night.",
    longDescription: [
      "Sobremesa — the Portuguese word for the time spent at the table after eating — seats eighteen people at one long table, once a night. The identity had to work in candlelight and survive wine.",
      "Menus are letterpressed on heavy linen-weave stock and change daily. The mark appears only twice: embroidered on the napkins and blind-debossed on the bill folder.",
    ],
    heroImage: "p-the-long-table-hero",
    heroFocal: "50% 50%",
    gallery: [
      { image: "p-the-long-table-01", caption: "The table, set for eighteen.", layout: "wide" },
      { image: "p-the-long-table-02", caption: "Plate, second course.", layout: "inset" },
      { image: "p-the-long-table-03", caption: "Glass and bread, before service.", layout: "pair" },
      { image: "p-the-long-table-04", caption: "Daily menu, letterpress.", layout: "pair" },
      { image: "p-the-long-table-05", caption: "Napkin folds, embroidered mark.", layout: "full" },
    ],
    role: "Identity, printed matter, table objects",
    team: ["Mira Solberg", "Tomás Vale"],
    deliverables: ["Identity", "Letterpress menus", "Embroidered linen", "Signage"],
    credits: [{ role: "Letterpress", name: "Oficina Tipo" }],
    featured: false,
    sortOrder: 7,
    related: ["tidewater", "field-notes-on-clay"],
  },
  {
    title: "Paper Weather",
    slug: "paper-weather",
    client: "Self-initiated",
    year: 2022,
    category: "Editorial",
    discipline: "Print series",
    location: "Lisbon",
    thesis: "A year of weather reports, printed in three inks.",
    shortDescription:
      "A self-initiated risograph series translating a year of Lisbon weather into colour and form.",
    longDescription: [
      "Every Sunday for a year, the studio printed one sheet describing the past week's weather — rainfall as a vermilion band, wind as misregistration, sunlight as yellow.",
      "Fifty-two sheets became a boxed set and a small exhibition. It remains the project we point to when people ask how we think about systems: simple rules, honest inputs, results we could not have drawn by hand.",
    ],
    heroImage: "p-paper-weather-hero",
    heroFocal: "50% 50%",
    gallery: [
      { image: "p-paper-weather-01", caption: "Week 14 — a wet April.", layout: "portrait" },
      { image: "p-paper-weather-02", caption: "Weeks 30 to 32 hung together.", layout: "wide" },
      {
        image: "p-paper-weather-03",
        caption: "Halftone detail, yellow over blue.",
        layout: "inset",
      },
      { image: "p-paper-weather-04", caption: "Poster for the exhibition.", layout: "pair" },
      { image: "p-paper-weather-05", caption: "Misregistration as wind.", layout: "pair" },
    ],
    role: "Concept, design, printing",
    team: ["Mira Solberg"],
    deliverables: ["52 risograph prints", "Boxed edition of 60", "Exhibition"],
    credits: [{ role: "Printing", name: "Noiré studio riso" }],
    featured: false,
    sortOrder: 8,
    related: ["ninefold", "the-long-table"],
  },
];
